name: Build and Release LaTeX Document

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:  # Enables manual triggering
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex  # Adjust this to your main LaTeX file

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf

  release_pdf:
    needs: build
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download PDF from Artifacts
      uses: actions/download-artifact@v4
      with:
        name: PDF

    - name: Generate Tag Name
      id: tag_name
      run: echo "tag_name=$(date +'%Y%m%d-%H%M%S')-$(echo $GITHUB_RUN_ID)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag_name }}
        release_name: Release ${{ env.tag_name }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
